-- SQL RETAIL SALES ANALYSIS - P1 
CREATE DATABASE sql_prroject_p1;

-- CREATING TABLE
DROP TABLE IF EXISTS RATAIL_SALES;
CREATE TABLE RETAIL_SALES
				(
					transactions_id	INT,
					sale_date DATE,
					sale_time TIME,
					customer_id	INT,
					gender VARCHAR(15),
					age INT,
					category VARCHAR(15),	
					quantiy	INT,
					price_per_unit	FLOAT,
					cogs	FLOAT,
					total_sale FLOAT

				)
SELECT * FROM RETAIL_SALES;

--IMPORTING CSV 
BULK INSERT RETAIL_SALES
FROM 'C:\Users\Rohan\Downloads\SQL - Retail Sales Analysis_utf .csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n'
);
SELECT TOP 10 *
FROM RETAIL_SALES;

SELECT COUNT(*) FROM RETAIL_SALES;

--DEALING WITH NULL VALUES
SELECT *
FROM RETAIL_SALES
WHERE transactions_id IS NULL
   OR sale_date IS NULL
   OR sale_time IS NULL
   OR customer_id IS NULL
   OR gender IS NULL
   OR age IS NULL
   OR category IS NULL
   OR quantiy IS NULL
   OR price_per_unit IS NULL
   OR cogs IS NULL
   OR total_sale IS NULL;

   -- CLEANING DATA 
DELETE
FROM RETAIL_SALES
WHERE quantiy IS NULL
  AND price_per_unit IS NULL
  AND cogs IS NULL
  AND total_sale IS NULL;

SELECT COUNT(*) FROM RETAIL_SALES;

-- HANDLING THE MISSING VALUES IN AGE COLUMN

SELECT COUNT(*) AS null_age_count
FROM RETAIL_SALES
WHERE age IS NULL;

UPDATE RETAIL_SALES
SET age = (
    SELECT AVG(age)
    FROM RETAIL_SALES
    WHERE age IS NOT NULL
)
WHERE age IS NULL;

--DATA EXPLORATION

--HOW MANY SALES WE HAVE
SELECT COUNT(*) AS TOTAL_SALE FROM RETAIL_SALES

--HOW MANY UNIQUE COSTUMERS WE HAVE
SELECT COUNT(DISTINCT customer_id) as total_sale FROM RETAIL_SALES;

SELECT COUNT(DISTINCT category) as total_sale FROM RETAIL_SALES;

--DATA ANALYSIS : BUSINESS KEY PROBLEMS AND ANSWERS:

--1.  WRITE A SQL QUERRY TO RETRIEVE ALL COLUMNS FOR SALES MADE ON '2022-11-05' :
SELECT *
FROM RETAIL_SALES
WHERE sale_date='2022-11-05';

--2. WRITE A SQL QUERRY TO RETRIEVE ALLTRANSACTIONS WHERE THE CATEGORY IS CLOTHING AND THE AUANTITY SOLD IS MORE THAN 4 IN THE MONTH OF NOV-22
SELECT *
FROM RETAIL_SALES
WHERE category='Clothing' 
AND quantiy>=4 
AND FORMAT(sale_date, 'yyyy-MM') = '2022-11';

--3. WRITE SQL QUERRY TO CALCULATE THE TOTAL SALES FOR EACH CATEGORY:
SELECT category,SUM(total_sale) AS NET_SALE
FROM RETAIL_SALES 
GROUP BY category

--4. WRITE A SQL QUERRY TO FIND THE AVERAGE AGE OF CUSTOMERS WHO PURCHASED ITEMS FROM THE 'BEAUTY' CATEGORY:
SELECT category, AVG(age) AS AVG_AGE
FROM RETAIL_SALES
WHERE category='Beauty'
GROUP BY category

--5. WRITE A SQL QUERRY TO FIND ALL TRANSACTIONS WHERE THE total_sale IS GREATER THAN 1000:
SELECT *
FROM RETAIL_SALES
WHERE total_sale>1000 ;

--6. WRITE A SQL QUERRY TO FIND THE TOTAL NUMBER OF TRANSACTIONS(ID) MADE BY EACH GENDER IN EACH CATEGORY:
SELECT DISTINCT  category ,gender, SUM(transactions_id) AS TOTAL_TRANSACTIONS
from RETAIL_SALES 
GROUP BY category,gender

--7. WRITE A SQL QUERRY TO CALCULATE THE AVERAGE SALE FOR EACH MONTH ALSO FIND THE BEST SELLING MONTH IN EACH YEAR:
SELECT 
	year,
	month,
	AVG_sales
	FROM 
	(
	SELECT
		YEAR(sale_date)  AS year,
		MONTH(sale_date) AS month,
		AVG(total_sale)  AS AVG_sales,
		RANK() OVER(PARTITION BY YEAR(sale_date) ORDER BY AVG(total_sale) DESC) AS rank
	FROM RETAIL_SALES
	GROUP BY 
		YEAR(sale_date),
		MONTH(sale_date)
		) AS t1
	WHERE rank=1
 
--8. WRITE A SQL QUERRY TO FIND THE TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL SALES
SELECT TOP 5
	customer_id,
	SUM(total_sale) AS TOTAL_SALES
FROM RETAIL_SALES
GROUP BY customer_id
ORDER BY TOTAL_SALES DESC

--9. WRITE A SQL QUERRY TO FIND THE NUMBER OF UNIQUE CUSTOMERS WHO PURCHASED ITEMS FROM EACH CATEGORY
SELECT 
	category,
	COUNT(DISTINCT customer_id) AS UNIQUE_CUSTOMERS
FROM RETAIL_SALES
GROUP BY category

--10. WRITE A SQL QUERRY TO CREATE EACH SHIFT ABD NUMBER OF ORDERS (EXAMPLE MORNING<=12 , AFTERNOON BEETWEEN 12&17, EVENING >17)
SELECT 
    CASE 
        WHEN DATEPART(HOUR, sale_time) < 12 THEN 'Morning'
        WHEN DATEPART(HOUR, sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
        ELSE 'Evening'
    END AS shift,
    COUNT(*) AS total_orders
FROM retail_sales
GROUP BY 
    CASE 
        WHEN DATEPART(HOUR, sale_time) < 12 THEN 'Morning'
        WHEN DATEPART(HOUR, sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
        ELSE 'Evening'
    END;



